cd c:\ruby_project
c:\ruby\bin\ruby.exe taobaoImporter.rb 	1	1 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	2	2 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	3	3 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	4	4 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	5	5 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	6	6 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	7	7 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	8	8 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	9	9 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	10	10 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	11	11 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	12	12 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	13	13 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	14	14 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	15	15 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	16	16 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	17	17 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	18	18 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	19	19 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	20	20 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	21	21 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	22	22 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	23	23 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	24	24 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	25	25 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	26	26 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	27	27 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	28	28 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	29	29 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	30	30 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	31	31 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	32	32 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	33	33 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	34	34 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	35	35 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	36	36 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	37	37 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	38	38 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	39	39 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	40	40 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	41	41 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	42	42 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	43	43 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	44	44 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	45	45 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	46	46 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	47	47 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	48	48 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	49	49 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	50	50 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	51	51 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	52	52 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	53	53 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	54	54 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	55	55 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	56	56 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	57	57 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	58	58 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	59	59 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	60	60 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	61	61 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	62	62 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	63	63 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	64	64 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	65	65 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	66	66 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	67	67 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	68	68 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	69	69 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	70	70 -b 
c:\ruby\bin\ruby.exe taobaoImporter.rb 	71	71 -b 
